### ISSUE TITLE
Padrino:: latest mongoid_taggable doesn't provide tagged_with method

### ISSUE THREAD

**Issue by wakatara** [wilkerlucio/mongoid_taggable#14]
My Gemfile tried to contain both
gem 'mongoid_taggable'

and 

gem 'mongoid_taggable', :require => 'mongoid/taggable'

and while tagging in the admin views worked and they are saved in models, I am continually told that a tagged_with method does not exist on the class. Pretty sure this is a bug.

Have switched to this gist for meantime but it does work:
http://pemberthy.blogspot.com/2010/03/adding-tags-to-mongoid-documents.html

**Comment by wakatara** [comment]
Actually, thinking this may be a problem with your gemspec. 0.14 doesn't have a tagged_with method available and I noticed you included lib/taggable.rb twice in gemspec files. Trying to ue the master branch to get the gem to see if that gives me the scope method now.

**Comment by wilkerlucio** [comment]
Thanks for noticing, fixed on version 0.1.5 ;)

**Comment by wakatara** [comment]
Cool. Pulling now. Saved me building tagging functions myself. =p

Are you merging or actively looking at the other fork that's made some changes to the way yours works? Just curious.

**Comment by wilkerlucio** [comment]
Yeah, I took some look on others forks, but even liking some changes, there are many others that I don't... Mainly because some of them change the way that I mean it should go, and others because compatibility breaks with old Mongoid versions. But I'm always open to look at new pull requests, specially, I'll be very happy to receive a simple pull request implementing dirty attributes (as discussed on issue #7). They did this implementation on other fork, but costing a lot of other things, this is why I don't merged...
